create table sensor
(
    id int primary key generated by default as identity,
    name varchar(30) unique check (length(name) between 3 and 30)
);
create table measurement(
                            id int primary key generated by default as identity,
                            value numeric(2) check ( value between -100 and 100),
                            raining boolean not null,
                            sensor varchar references sensor(name) not null,
                            measured_at timestamp
);